import React,{useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {ArrowLeft,Save} from 'lucide-react';
import {mutate} from './api.js';
import {Heading,useApp} from './App.jsx';
import {ErrorNote,Field,ImageField,RichEditor} from './ui.jsx';

const slugify=value=>value.toLowerCase().trim().replace(/['’]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,180);
const list=value=>value.split(',').map(item=>item.trim()).filter(Boolean);
export default function NewPost(){
 const navigate=useNavigate(),{notify}=useApp();const [tab,setTab]=useState('content'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[slugTouched,setSlugTouched]=useState(false);
 const [post,setPost]=useState({title:'',slug:'',excerpt:'',body:'',status:'draft',publishDate:new Date().toISOString().slice(0,10),featured:false,categories:'',tags:'',featuredImage:'',authorName:'',authorAvatar:'',authorBio:'',relatedProducts:'',relatedCategories:'',relatedBrands:'',seoTitle:'',seoDescription:'',canonical:'',focusKeyword:'',robots:'index,follow',maxImagePreview:'large',ogTitle:'',ogDescription:'',ogImage:'',twitterTitle:'',twitterDescription:''});
 const set=(key,value)=>setPost(current=>({...current,[key]:value}));
 const title=value=>{setPost(current=>({...current,title:value,slug:slugTouched?current.slug:slugify(value)}))};
 async function submit(event){event.preventDefault();setBusy(true);setError('');try{const saved=await mutate('/admin/pages',{title:post.title,path:`/${post.slug}`,excerpt:post.excerpt,body:post.body,status:post.status,publishDate:post.publishDate,featured:post.featured,categories:list(post.categories),tags:list(post.tags),featuredImage:post.featuredImage,author:{name:post.authorName,avatar:post.authorAvatar,bio:post.authorBio},relatedProducts:list(post.relatedProducts),relatedCategories:list(post.relatedCategories),relatedBrands:list(post.relatedBrands),seo:{title:post.seoTitle,description:post.seoDescription,canonical:post.canonical,focusKeyword:post.focusKeyword,robots:post.robots,maxImagePreview:post.maxImagePreview,ogTitle:post.ogTitle,ogDescription:post.ogDescription,ogImage:post.ogImage,twitterTitle:post.twitterTitle,twitterDescription:post.twitterDescription}});notify(post.status==='published'?'Post published':'Post draft created');navigate('/pages/'+saved.id)}catch(error){setError(error)}finally{setBusy(false)}}
 return <form onSubmit={submit} className="new-post">
  <Link className="back-link" to="/blogs"><ArrowLeft size={16}/>Blog posts</Link>
  <Heading eyebrow="CONTENT / BLOG POSTS" title="New post" description="Create an article using the existing BG Elevators blog layout."><Link className="button" to="/blogs">Cancel</Link><button className="primary" disabled={busy}><Save size={16}/>{busy?'Creating…':post.status==='published'?'Create & publish':'Create post'}</button></Heading>
  <ErrorNote error={error}/><div className="tabs" role="tablist">{[['content','Content'],['author','Author & related'],['seo','SEO']].map(([id,label])=><button type="button" role="tab" aria-selected={tab===id} className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {tab==='content'&&<div className="new-post-grid"><div className="form-stack card"><Field label="Title"><input required value={post.title} onChange={e=>title(e.target.value)}/></Field><Field label="Slug" hint="Clean public URL without ."><div className="slug-input"><span>/</span><input required pattern="[a-z0-9][a-z0-9-]*" value={post.slug} onChange={e=>{setSlugTouched(true);set('slug',slugify(e.target.value))}}/></div></Field><Field label="Excerpt" hint={`${post.excerpt.length} / 600`}><textarea rows="4" maxLength="600" value={post.excerpt} onChange={e=>set('excerpt',e.target.value)}/></Field><Field label="Body"><RichEditor value={post.body} onChange={value=>set('body',value)}/></Field></div><aside className="new-post-side"><section className="card form-stack"><h2>Publishing</h2><Field label="Status"><select value={post.status} onChange={e=>set('status',e.target.value)}><option value="draft">Draft</option><option value="published">Published</option></select></Field><Field label="Publish date"><input type="date" value={post.publishDate} onChange={e=>set('publishDate',e.target.value)}/></Field><label className="check"><input type="checkbox" checked={post.featured} onChange={e=>set('featured',e.target.checked)}/>Featured post</label></section><section className="card form-stack"><h2>Taxonomy</h2><Field label="Categories" hint="Comma-separated"><input value={post.categories} onChange={e=>set('categories',e.target.value)}/></Field><Field label="Tags" hint="Comma-separated"><input value={post.tags} onChange={e=>set('tags',e.target.value)}/></Field></section><section className="card form-stack"><h2>Featured image</h2><ImageField value={post.featuredImage} onChange={value=>set('featuredImage',value)} label="Image"/></section></aside></div>}
  {tab==='author'&&<div className="form-stack card"><h2>Author</h2><div className="two-fields"><Field label="Name"><input value={post.authorName} onChange={e=>set('authorName',e.target.value)}/></Field><ImageField value={post.authorAvatar} onChange={value=>set('authorAvatar',value)} label="Avatar"/></div><Field label="Bio"><textarea rows="5" value={post.authorBio} onChange={e=>set('authorBio',e.target.value)}/></Field><h2>Related content</h2><Field label="Related products" hint="Comma-separated names or URLs"><input value={post.relatedProducts} onChange={e=>set('relatedProducts',e.target.value)}/></Field><Field label="Related categories" hint="Comma-separated"><input value={post.relatedCategories} onChange={e=>set('relatedCategories',e.target.value)}/></Field><Field label="Related brands" hint="Comma-separated"><input value={post.relatedBrands} onChange={e=>set('relatedBrands',e.target.value)}/></Field></div>}
  {tab==='seo'&&<div className="form-stack card"><div className="search-preview"><small>{post.canonical||`https://bgelevators.com/${post.slug||'post-slug'}`}</small><h3>{post.seoTitle||post.title||'Page title'}</h3><p>{post.seoDescription||post.excerpt||'Meta description will appear here.'}</p></div><Field label="Meta title" hint={`${post.seoTitle.length} / 60`}><input maxLength="60" value={post.seoTitle} onChange={e=>set('seoTitle',e.target.value)}/></Field><Field label="Meta description" hint={`${post.seoDescription.length} / 160`}><textarea rows="3" maxLength="160" value={post.seoDescription} onChange={e=>set('seoDescription',e.target.value)}/></Field><div className="two-fields"><Field label="Canonical URL"><input type="url" value={post.canonical} onChange={e=>set('canonical',e.target.value)}/></Field><Field label="Focus topic / keyword"><input value={post.focusKeyword} onChange={e=>set('focusKeyword',e.target.value)}/></Field></div><div className="two-fields"><Field label="Robots"><select value={post.robots} onChange={e=>set('robots',e.target.value)}><option value="index,follow">Index, follow</option><option value="noindex,follow">Noindex, follow</option><option value="noindex,nofollow">Noindex, nofollow</option></select></Field><Field label="Max image preview"><select value={post.maxImagePreview} onChange={e=>set('maxImagePreview',e.target.value)}><option value="large">Large</option><option value="standard">Standard</option><option value="none">None</option></select></Field></div><h2>Open Graph</h2><div className="two-fields"><Field label="OG title"><input value={post.ogTitle} onChange={e=>set('ogTitle',e.target.value)}/></Field><Field label="OG description"><input value={post.ogDescription} onChange={e=>set('ogDescription',e.target.value)}/></Field></div><ImageField value={post.ogImage} onChange={value=>set('ogImage',value)} label="OG image"/><h2>X / Twitter</h2><div className="two-fields"><Field label="Title"><input value={post.twitterTitle} onChange={e=>set('twitterTitle',e.target.value)}/></Field><Field label="Description"><input value={post.twitterDescription} onChange={e=>set('twitterDescription',e.target.value)}/></Field></div></div>}
 </form>;
}
