import React,{useEffect,useRef,useState} from 'react';
import {X,Upload,Search,Image as ImageIcon,Bold,Italic,List,Link as LinkIcon,Code} from 'lucide-react';
import {api} from './api.js';
export function Field({label,children,hint}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function Badge({children,tone=''}){return <span className={'badge '+tone}>{children}</span>}
export function Empty({title='Nothing here yet',text}){return <div className="empty"><ImageIcon size={32}/><h3>{title}</h3>{text&&<p>{text}</p>}</div>}
export function ErrorNote({error}){return error?<div className="error" role="alert">{error.message||error}</div>:null}
export function Loading(){return <div className="loading" role="status">Loading…</div>}
export function Modal({title,children,onClose,wide=false,fullscreen=false}){const ref=useRef(null);useEffect(()=>{ref.current.showModal();return()=>ref.current?.close()},[]);return <dialog className={'dialog'+(wide?' wide':'')+(fullscreen?' fullscreen':'')} ref={ref} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}}><header><h2>{title}</h2><button className="icon-btn" aria-label="Close" onClick={onClose}><X size={20}/></button></header>{children}</dialog>}
export function RichEditor({value,onChange}){const ref=useRef(null);const [source,setSource]=useState(false);useEffect(()=>{if(ref.current&&ref.current.innerHTML!==value)ref.current.innerHTML=value},[value,source]);
 function command(cmd,arg){ref.current.focus();document.execCommand(cmd,false,arg);onChange(ref.current.innerHTML)}
 return <div className="rich-editor"><div className="editor-tools">{[['bold',Bold,'Bold'],['italic',Italic,'Italic'],['insertUnorderedList',List,'Bullet list']].map(([cmd,Icon,label])=><button type="button" key={cmd} aria-label={label} onMouseDown={e=>e.preventDefault()} onClick={()=>command(cmd)}><Icon size={17}/></button>)}<select aria-label="Paragraph style" onChange={e=>command('formatBlock',e.target.value)} defaultValue="p"><option value="p">Paragraph</option><option value="h2">Heading 2</option><option value="h3">Heading 3</option></select><button type="button" aria-label="Insert link" onClick={()=>{const href=prompt('Link URL');if(href)command('createLink',href)}}><LinkIcon size={17}/></button><button type="button" className={source?'selected':''} onClick={()=>setSource(!source)}><Code size={16}/> HTML</button></div>{source?<textarea rows={16} aria-label="HTML content" value={value} onChange={e=>onChange(e.target.value)}/>:<div ref={ref} className="rich-area" contentEditable suppressContentEditableWarning role="textbox" aria-multiline="true" aria-label="Formatted content" onInput={()=>onChange(ref.current.innerHTML)} onPaste={e=>{e.preventDefault();command('insertText',e.clipboardData.getData('text/plain'))}}/>}</div>
}
export function MediaPicker({onSelect,onClose}){const [items,setItems]=useState([]),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{api('/admin/media').then(setItems).catch(setError)},[]);
 async function upload(e){const file=e.target.files[0];if(!file)return;setBusy(true);setError('');try{const form=new FormData();form.set('file',file);const item=await api('/admin/media/upload',{method:'POST',body:form});setItems(x=>[item,...x]);}catch(e){setError(e)}finally{setBusy(false)}}
 return <Modal title="Choose media" wide onClose={onClose}><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search files" value={query} onChange={e=>setQuery(e.target.value)}/></div><label className="button primary"><Upload size={16}/>{busy?'Uploading…':'Upload file'}<input type="file" hidden accept="image/png,image/jpeg,image/webp,application/pdf" onChange={upload} disabled={busy}/></label></div><ErrorNote error={error}/><div className="media-grid picker">{items.filter(i=>i.name.toLowerCase().includes(query.toLowerCase())).map(i=><button key={i.id} className="media-tile" onClick={()=>onSelect(i)}><div className="media-image">{i.type.startsWith('image/')?<img src={i.url} alt={i.alt||i.name} loading="lazy"/>:<span>PDF</span>}</div><span>{i.name}</span></button>)}</div></Modal>
}
export function ImageField({value,onChange,label='Image'}){const [picker,setPicker]=useState(false);return <div className="image-field"><Field label={label}><div className="image-input">{value&&<img src={value} alt="Selected" loading="lazy"/>}<input value={value||''} onChange={e=>onChange(e.target.value)} placeholder="/images/example.webp or https://…"/><button type="button" onClick={()=>setPicker(true)}>Choose</button></div></Field>{picker&&<MediaPicker onClose={()=>setPicker(false)} onSelect={i=>{onChange(i.url);setPicker(false)}}/>}</div>}
